apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim
  namespace: project
spec:
  storageClassName: nodeserverpics-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi