apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 3001