apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup-job
  namespace: project
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-backup
            image: google/cloud-sdk:latest 
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/bucket-key.json
            volumeMounts:
            - name: gcs-credentials
              mountPath: /var/secrets/google
              readOnly: true
            command:
              - /bin/sh
              - -c
              - |
                apt-get update && apt-get install -y wget gnupg && \
                
                echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
                wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg && \
                echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
                
                apt-get update && apt-get install -y postgresql-client-17 && \

                export BACKUP_FILE="/tmp/db_backup_$(date +\%Y\%m\%d\%H\%M\%S).sql" && \

                pg_dump -h postgres-service -U $POSTGRES_USER -d projectdb > $BACKUP_FILE && \

                gsutil -D cp $BACKUP_FILE gs://devops-kubernetes-backups/ && \

                rm $BACKUP_FILE
          restartPolicy: OnFailure
          volumes:
          - name: gcs-credentials
            secret:
              secretName: gcs-credentials

