apiVersion: v1
kind: Service
metadata:
  name: log-output-service
spec:
  type: LoadBalancer  
  selector:
    app: log-output-app
  labels:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 3001