apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-app
  labels:
    app: node-server-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: node-server-app
  template:
    metadata:
      labels:
        app: node-server-app
    spec:
      containers:
      - name: node-server
        image: juhosii/devops-kubernetes:1.05  
        ports:
        - containerPort: 3001  
        env:
        - name: PORT
          value: "3000"  
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"