apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 3001