apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  namespace: logoutput
spec:
  type: NodePort
  selector:
    app: log-output-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 3001