apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: project
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-claim
      containers:
      - name: backend
        image: juhosii/devops-kubernetes:2.10.2
        env:
          - name: DB_HOST
            value: "postgres-service.project"
          - name: DB_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            value: "projectdb"
        ports:
        - containerPort: 3001 
       