apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodeserver-pvc
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-local-pv
  resources:
    requests:
      storage: 200Mi