apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
  namespace: project
spec:
  metrics:
    - name: cpu-usage
      initialDelay: 10m
      successCondition: result < 0.99
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
          query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[10m])))